export const GET_USER_LOGIN_DATA_REQUEST = "GET_USER_LOGIN_DATA_REQUEST";
export const GET_USER_LOGIN_DATA_SUCCESS = "GET_USER_LOGIN_DATA_SUCCESS";
export const GET_USER_LOGIN_DATA_FAILURE = "GET_USER_LOGIN_DATA_FAILURE";

export const POST_USER_LOGIN_DATA_REQUEST = "POST_USER_LOGIN_DATA_REQUEST";
export const POST_USER_LOGIN_DATA_SUCCESS = "POST_USER_LOGIN_DATA_SUCCESS";
export const POST_USER_LOGIN_DATA_FAILURE = "POST_USER_LOGIN_DATA_FAILURE";